### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by Tischel**
* Changelog window shows up automatically the first time a new version is loaded
* Cleaned up config window layout and added a changelog button
* Fixed crash when opening browser

image
image

### CODE REVIEW

**Comment by Tischel** [comment]
> I really like it! Only thing I'd consider would be having the "big stuff" earlier in the changelog such as partyframes and profiles. Maybe a "highlights" section?

Ah yea, that's a good idea.
I kinda did it in chronological order but prob better to re-organize it a bit.

**Comment by Tischel** [comment]
Re-organized the changelog a bit:
https://github.com/DelvUI/DelvUI/blob/f79a8fb18a1729da2d7a42c6472dea919394b438/DelvUI/changelog.md

**Comment by Kanubiz** [comment]
Hmm i would probably change the style of the hide and unlock hud buttons if we're leaving a clean mask on the changelog button

**Comment by Tischel** [comment]
> > Would also add a "See what's new!" Headline to the changelog
> 
> And format it a little better, can use the ascii icon i used for the collapsibles instead of the -

It's markdown

**Pull request merged**
