### PR TITLE
Drag and Drop attributes + SAM buffs and sen ordering

### PR DESCRIPTION
**Pull request by chipget**
Adds DragDropHorizontalAttribute and gives two examples: SAM shifu/jinpu order and SAM sen order.

This is a refactor of pull request #271 under the new configuration system.

### CODE REVIEW

**Comment by chipget** [comment]
Can I ask why this was closed? I understand the other PR being closed since this is a refactor of that one, but t is there something wrong with the commit?

**Comment by jdsmith2816** [comment]
Hey, this wasn't intended to be closed.  I'm unsure why github did it automatically.

**Comment by jdsmith2816** [comment]
Alright @chipget @abazilla the major hudwindow and config refactors have landed. If you're still interested in a system like this now's the time to re-acquaint yourself with how things work and open a PR against beta2.  

Sorry for all of the churn here;  i know it's been alot but it's been prettymuch unavoidable.

Pinging @Tischel in case he might want to chip in on any idea you come up with.

**Comment by jdsmith2816** [comment]
ohh i see why this is being autoclosed.... branches get deleted on merge and i just merged dev to master

**Comment by chipget** [comment]
I've finished the refactor and am posting a new pull request.

**Pull request closed without merging**
