### PR TITLE
Correct ingame Job Order in config, HUDManager code cleanup

### PR DESCRIPTION
**Pull request by Zeffuro**
Corrects the job order in the configuration window to the correct order ingame.
Rider code cleanup on HudManager.cs

### CODE REVIEW

**Comment by Tischel** [comment]
You should only push the changes of the lines you're touching IMO.
The diff looks crazy due to Rider's auto editor I assume.

**Comment by Zeffuro** [comment]
> You should only push the changes of the lines you're touching IMO.
> The diff looks crazy due to Rider's auto editor I assume.

But then it will complain about var use etc.

**Comment by Zeffuro** [comment]
Discussion on style/code usage: <https://discord.com/channels/878296899331973120/878298582220959765/886249657192288316>

Please let me know if I should redo this and ignore styling or if we commit this.

**Comment by Zeffuro** [comment]
Rejecting

**Pull request closed without merging**
