### PR TITLE
Feature: profiles & job-specific profiles

### PR DESCRIPTION
**Pull request by nilaykumar**
Replaces the Import/Export pane with a Profiles pane (let me emphasize that the UI is _completely provisional_ at the moment and just a stand-in to test the functionality), which:
- allows for creating new profiles (from default or from clipboard)
- allows for deletion of profiles
- allows for linking a job to a profile

Profiles are updated when the config window is used to change parameters and are saved to disk just like all other configurations.
I've also refactored some of the import/export code to clean up ConfigurationManager.

I haven't had a chance to test extensively, so testing, comments, and suggestions are appreciated.

**Known issues**:

1. Switching to a job that has a job-specific profile associated to it causes about half a second of lag. This is because we have to load the configuration from the import string for that profile --- this involves decompressing the base64 and parsing the JSON.

image

### CODE REVIEW

**Comment by oratory** [comment]
I played around with this a bit. Wago is updated (locally) with the new profile strings.

**Bugs:**
Deleting a profile seems hit or miss. It seems to work fairly regularly if it's the first action taken (load DelvUI > Profiles Tab > Remove) but if you delete a second profile, or import/select a profile and then delete one, it will usually crash the plugin requiring a game restart.

**Suggestions:**
Add some sort of user feedback when clicking Export, maybe something simple like briefly changing the icon color (like a button) or show a message indicating the string is now in the Clipboard.

Add a confirmation on delete.

Instead of the 'Import as this name' field, include the profile name in the import string itself and use that name when importing (ask before overwriting an existing profile).

**Comment by nilaykumar** [comment]
Thanks for the feedback!

> Deleting a profile seems hit or miss. It seems to work fairly regularly if it's the first action taken (load DelvUI > Profiles Tab > Remove) but if you delete a second profile, or import/select a profile and then delete one, it will usually crash the plugin requiring a game restart.

Aha, thanks for tracking this down! When I get the chance, I'll try to reproduce this and then figure out what's going on. Probably an index out of bounds somewhere (do you happen to know where, from the log?)

> Add some sort of user feedback when clicking Export, maybe something simple like briefly changing the icon color (like a button) or show a message indicating the string is now in the Clipboard.
> 
> Add a confirmation on delete.

I don't know too much about ImGui so maybe for now I'll try to leave a message in the chat window for things like this. I'll leave the visual/popup feedback to the gui experts. For text-based confirmation on delete I could look for double click, but maybe I'll just leave it unimplemented for now.

> Instead of the 'Import as this name' field, include the profile name in the import string itself and use that name when importing (ask before overwriting an existing profile).

This sounds reasonable. In this case I might Export/Remove column to an Actions column which has combo boxes with options to Export/Remove/Rename/etc. to minimize clutter (I was planning on doing something like this anyway).

**Comment by oratory** [comment]
Ah yes, here's the error:
```
[ERR] [DelvUI] UiBuilder OnBuildUi caught exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DelvUI.Config.ProfilesConfig.<>c__DisplayClass11_2.<DrawProfile>b__11(String o) in D:\a\DelvUI\DelvUI\DelvUI\Config\ProfilesConfig.cs:line 278
   at System.Array.FindIndex[T](T[] array, Int32 startIndex, Int32 count, Predicate`1 match)
   at System.Array.FindIndex[T](T[] array, Predicate`1 match)
   at DelvUI.Config.ProfilesConfig.DrawProfile() in D:\a\DelvUI\DelvUI\DelvUI\Config\ProfilesConfig.cs:line 0
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at DelvUI.Config.Tree.ConfigPageNode.DrawWithID(Boolean& changed, String ID) in D:\a\DelvUI\DelvUI\DelvUI\Config\Tree\ConfigNode.cs:line 890
   at DelvUI.Config.Tree.ConfigPageNode.Draw(Boolean& changed) in D:\a\DelvUI\DelvUI\DelvUI\Config\Tree\ConfigNode.cs:line 794
   at DelvUI.Config.Tree.NestedSubSectionNode.DrawSubConfig(Boolean& changed) in D:\a\DelvUI\DelvUI\DelvUI\Config\Tree\ConfigNode.cs:line 630
   at DelvUI.Config.Tree.NestedSubSectionNode.Draw(Boolean& changed) in D:\a\DelvUI\DelvUI\DelvUI\Config\Tree\ConfigNode.cs:line 605
   at DelvUI.Config.Tree.SectionNode.Draw(Boolean& changed) in D:\a\DelvUI\DelvUI\DelvUI\Config\Tree\ConfigNode.cs:line 459
   at DelvUI.Config.Tree.BaseNode.Draw() in D:\a\DelvUI\DelvUI\DelvUI\Config\Tree\ConfigNode.cs:line 273
   at DelvUI.Config.ConfigurationManager.Draw() in D:\a\DelvUI\DelvUI\DelvUI\Config\ConfigurationManager.cs:line 183
   at DelvUI.Plugin.Draw() in D:\a\DelvUI\DelvUI\DelvUI\Plugin.cs:line 183
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 234```

**Comment by jdsmith2816** [comment]
@nilaykumar Could you go ahead and convert this to draft until we're ready to review again?

**Comment by jdsmith2816** [comment]
@nilaykumar github autoclosed these PRs when I merged beta2;  please reopen these changes to beta3 branch with any relevant updates and we can get them merged in

**Pull request closed without merging**
