### PR TITLE
White Mage HUD Tweaks

### PR DESCRIPTION
**Pull request by pascbeck**
-  added checkbox to remove dia timer
-  added custom pandemic refresh option 
-  added option to disable dia bar outside of active state

### CODE REVIEW

**Review by Kanubiz — CHANGES_REQUESTED** [review]
Your configs are not properly ordered, check out the other jobs like PLD to have a feel on how the order should look like

**Comment by pascbeck** [comment]
Thanks, hopefully it does fit now. @Kanubiz

**Comment by pascbeck** [comment]
image

**Review by jdsmith2816 — CHANGES_REQUESTED** [review]
These changes look fine imo but I'd like to delay merging until after beta2 goes out latter today or tomorrow.   Just flagging as change request so that it doesn't end up being merged by anyone.

**Comment by jdsmith2816** [comment]
@pascbeck github autoclosed these PRs when I merged beta2;  please reopen these changes to beta3 branch with any relevant updates and we can get them merged in

**Pull request closed without merging**
