### PR TITLE
Add support for Japanese/Chinese and Korean (provided font is there)

### PR DESCRIPTION
**Pull request by Zeffuro**

### CODE REVIEW

**Comment by Zeffuro** [comment]
[UTF8 encoding](https://trello.com/c/MlpHKZzT/125-utf8-encoding)

**Comment by orocannoneer** [comment]
I just download beta2, it still shows question mark in Chinese name.
[https://i.imgur.com/AG7OWBB.png](url)

**Comment by vond82** [comment]
Problem seems to be that we don't provide a font with chinese symbols atm, it's being looked into

**Comment by orocannoneer** [comment]
> Problem seems to be that we don't provide a font with chinese symbols atm, it's being looked into

I tried to change Chinese font myself, but still shows question mark
[https://i.imgur.com/1AYiTuH.png](url)

**Comment by Zeffuro** [comment]
Just tested in Beta 2, these settings work for me.

Advanced_Combat_Tracker_2021-09-27_02-05-46

Advanced_Combat_Tracker_2021-09-27_02-06-26

Advanced_Combat_Tracker_2021-09-27_02-11-20

Maybe we do need more ranges though but that'd need extensive testing.

```
// GetGlyphRangesChineseFull() includes Default + Hiragana, Katakana, Half-Width, Selection of 1946 Ideographs
// https://skia.googlesource.com/external/github.com/ocornut/imgui/+/v1.53/extra_fonts/README.txt
builder.AddRanges(io.Fonts.GetGlyphRangesChineseFull());
```

Here is the font I used (combined font with most used Chinese and Japanese Glyphs) from Google's Noto Sans: https://puu.sh/Iebwm/69e6dd1aa4.ttf

**Comment by orocannoneer** [comment]
Oh...I didn't see font tab when I installed beta 2 first time.
Can see it after reinstall, it's OK now, thanks for help.

**Pull request merged**
