### PR TITLE
WHM :: added asylum, presence, plenary & temperance bars

### PR DESCRIPTION
**Pull request by pascbeck**
image

### CODE REVIEW

**Comment by pascbeck** [comment]
probably will have merge conflicts with #514

**Comment by vond82** [comment]
> probably will have merge conflicts with #514

Yep, shouldn't be too bad tho

**Comment by jdsmith2816** [comment]
@pascbeck Can you update your bar with respect to the changes I just merged?

@vond82 Please review when he finishes? You've been owning these lately so I don't want to just yolo merge it.

**Comment by vond82** [comment]
> @vond82 Please review when he finishes? You've been owning these lately so I don't want to just yolo merge it.

@jdsmith2816 I dont mind if you wanna merge it and i can put in a fix for those later tonight instead

**Pull request merged**
