### PR TITLE
Samurai Click-and-Drag Buffs and Sen Bar Ordering.

### PR DESCRIPTION
**Pull request by chipget**
This pull request adds click-and-drag buttons to the samurai configuration window, which swaps the ordering of the buff bars and the sen bars. For example, we can click and drag the button labeled "setsu" in the configuration window to swap it with "getsu", and the corresponding bars will swap positions. The same can be done with the "shifu/jinpu" buttons.

### CODE REVIEW

**Comment by chipget** [comment]
This pull request adds click-and-drag buttons to the samurai configuration window, which swaps the ordering of the buff bars and the sen bars. For example, we can click and drag the button labeled "setsu" in the configuration window to swap it with "getsu", and the corresponding bars will swap positions. The same can be done with the "shifu/jinpu" buttons.


orderex1
orderex2
oderex3

**Comment by jdsmith2816** [comment]
We're going to hold off on merging anything that touches much of the config stuff until after the refactor PRs are done.

**Review by jdsmith2816 — CHANGES_REQUESTED** [review]
flagging this as not ready for merge

**Comment by chipget** [comment]
This won't fit the new configuration style. To make this work, I'll make the drag and drop bars into a new Attribute.

**Comment by jdsmith2816** [comment]
Indeed.  Feel free to open a fresh PR targetting Dev and we can get it in as part of a beta1 patch release later in the week.  Maybe talk with abazilla as well since he seems to be trying to do something similar in https://github.com/DelvUI/DelvUI/pull/274

**Pull request closed without merging**
